language: node_js
node_js:
  - 4
  - 6
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_script:
  - npm install -g firebase-tools
script:
  - npm test
after_success:
  - npm run build
  - firebase deploy --token=${FIREBASE_API_TOKEN}